dist: precise
language: php

env:
  - DB=mysql

before_script:
  - ./tests/LDAP/ldap_run.sh
  - composer self-update
  - sed -e '/"php":/d' -i composer.json
  - rm -f composer.lock
  - composer install --optimize-autoloader
  # cannot disable mcrypt on travis...
  - sed -e "s/return extension_loaded('mcrypt');/return false;/" -i vendor/ircmaxell/random-lib/lib/RandomLib/AbstractMcryptMixer.php
  #install 0.72.3 database
  - mysql -u root -e 'create database glpitest0723;'
  - mysql -u root glpitest0723 < tests/glpi-0.72.3-empty.sql
  - cp tests/travis.config_db.php tests/config_db.php
  - php tools/cliupdate.php --config-dir=../tests --dev
  - rm tests/config_db.php
  - mysql -u root -e 'create database glpitest;'
  - php tools/cliinstall.php --db=glpitest --user=root --tests
  - php tools/cliupdate.php --config-dir=../tests |grep -q "No migration needed." || (echo "tools/cliupdate.php FAILED" && exit 1)
  - php -S localhost:8088 tests/router.php &>/dev/null &
  # LDAP stuff
  - phpenv config-add tests/enable-ldap.ini
  - ./tests/LDAP/ldap_fixtures.sh
script:
  - mysql -u root -e 'select version();'
  - vendor/bin/atoum --debug --bootstrap-file tests/bootstrap.php --no-code-coverage --max-children-number 1 -d tests/database
  - vendor/bin/atoum --debug --bootstrap-file tests/bootstrap.php --no-code-coverage --max-children-number 1 -d tests/units
  - vendor/bin/atoum --debug --bootstrap-file tests/bootstrap.php --no-code-coverage --max-children-number 1 -d tests/api
  - if [[ "$CS" == "true" ]]; then vendor/bin/phpcs -p --standard=vendor/glpi-project/coding-standard/GlpiStandard/ --ignore=/vendor/,/plugins/,/files/,/lib/,/config/,/tests/config ./; fi

#note: default maria version is 5.5 for all main php versions list exept nightly
matrix:
  include:
    - php: 5.6
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
    - php: 7.0
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
    - php: 7.1
      addons:
        mariadb: 10.0
        apt:
          packages:
            - ldap-utils
            - slapd
    - php: 7.1
      addons:
        mariadb: 10.1
        apt:
          packages:
            - ldap-utils
            - slapd
    - php: 7.1
      env: CS=true
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
    - php: nightly
      addons:
        apt:
          packages:
            - ldap-utils
            - slapd
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  irc:
    channels:
      - "chat.freenode.org#glpi"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

#exclude old branches, without tests
branches:
  except:
    - /^0\..*$/
